# Site settings
title: Ole J. Rosendahl
email: olejrosendahl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open-source projects, lists and ideas written by me. Some more complete
  than others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://olejrosendahl.github.io" # the base hostname & protocol for your site
twitter_username: olejrosendahl
github_username:  olejrosendahl

# Build settings
markdown: kramdown
